[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.30"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

# NOTE: Use https://github.com/joho/godotenv if https://github.com/joho/godotenv/pull/47 was merged.
[[constraint]]
  name = "github.com/sachaos/godotenv"
  branch = "feature-expand-variables-on-value"
