[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.30"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  branch = "master"
